### ISSUE TITLE
Can't bundle install capybara-webkit

### ISSUE THREAD

**Issue by sanemat** [sanemat/tachikoma#105]
In my private repo, I can't bundle install capybara-webkit.
I don't create minimal reproduce pattern, and my environment bases on docker container, so I don't know this is actual tachikoma's problem.

My ad-hoc solution is ignoring exit status:persevere:

docker container log:
```text
{"log":"Installing capybara 2.4.1\n","stream":"stdout","time":"2014-08-25T03:58:33.221076639Z"}
{"log":"/home/appuser/local/ruby-2.0/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/file_utils.rb:54:in `block in create_shell_runner': Command 
failed with status (): [bundle --gemfile Gemfile --no-deployment -...] (RuntimeError)\n","stream":"stderr","time":"2014-08-25T03:58:43.618150754Z"}
{"log":"\u0009from /home/appuser/local/ruby-2.0/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/file_utils.rb:45:in `call'\n","stream":"stderr","time":"2014-08-25T03:58:43.618150754Z"}
{"log":"\u0009from /home/appuser/local/ruby-2.0/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/file_utils.rb:45:in `sh'\n","stream":"stderr","time":"2014-08-25T03:58:43.618150754Z"}
{"log":"\u0009from /home/appuser/local/ruby-2.0/lib/ruby/gems/2.0.0/gems/tachikoma-4.2.0/lib/tachikoma/application.rb:77:in `block (2 levels) in bundle'\n","stream":"stderr","time":"2014-08-25T03:58:43.618150754Z"}
{"log":"\u0009from /home/appuser/local/ruby-2.0/lib/ruby/gems/2.0.0/gems/bundler-1.7.2/lib/bundler.rb:236:in `block in with_clean_env'\n","stream":"stderr","time":"2014-08-25T03:58:43.618150754Z"}
{"log":"\u0009from /home/appuser/local/ruby-2.0/lib/ruby/gems/2.0.0/gems/bundler-1.7.2/lib/bundler.rb:223:in `with_original_env'\n","stream":"stderr","time":"2014-08-25T03:58:43.618150754Z"}
{"log":"\u0009from /home/appuser/local/ruby-2.0/lib/ruby/gems/2.0.0/gems/bundler-1.7.2/lib/bundler.rb:229:in `with_clean_env'\n","stream":"stderr","time":"2014-08-25T03:58:43.618150754Z"}
{"log":"\u0009from /home/appuser/local/ruby-2.0/lib/ruby/gems/2.0.0/gems/tachikoma-4.2.0/lib/tachikoma/application.rb:72:in `block in bundle'\n","stream":"stderr","time":"2014-08-25T03:58:43.618150754Z"}
{"log":"\u0009from /home/appuser/local/ruby-2.0/lib/ruby/gems/2.0.0/gems/tachikoma-4.2.0/lib/tachikoma/application.rb:71:in `chdir'\n","stream":"stderr","time":"2014-08-25T03:58:43.618150754Z"}
{"log":"\u0009from /home/appuser/local/ruby-2.0/lib/ruby/gems/2.0.0/gems/tachikoma-4.2.0/lib/tachikoma/application.rb:71:in `bundle'\n","stream":"stderr","time":"2014-08-25T03:58:43.618150754Z"}
{"log":"\u0009from /code/github.com/sanemat/snake.tachikoma.io/lib/snake/cli.rb:95:in `snake_exec'\n","stream":"stderr","time":"2014-08-25T03:58:43.618150754Z"}
{"log":"\u0009from /code/github.com/sanemat/snake.tachikoma.io/lib/snake/cli.rb:20:in `tachikoma'\n","stream":"stderr","time":"2014-08-25T03:58:43.618150754Z"}
{"log":"\u0009from /home/appuser/local/ruby-2.0/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'\n","stream":"stderr","time":"2014-08-25T03:58:43.618150754Z"}
{"log":"\u0009from /home/appuser/local/ruby-2.0/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'\n","stream":"stderr","time":"2014-08-25T03:58:43.618150754Z"}
{"log":"\u0009from /home/appuser/local/ruby-2.0/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'\n","stream":"stderr","time":"2014-08-25T03:58:43.618150754Z"}
{"log":"\u0009from /home/appuser/local/ruby-2.0/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'\n","stream":"stderr","time":"2014-08-25T03:58:43.618150754Z"}
{"log":"\u0009from bin/snake:6:in `\u003cmain\u003e'\n","stream":"stderr","time":"2014-08-25T03:58:43.618150754Z"}
```

**Comment by sanemat** [comment]
This is caused the lack of vps' memory.
